// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcolor_hist.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XColor_hist_CfgInitialize(XColor_hist *InstancePtr, XColor_hist_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->Specs_BaseAddress = ConfigPtr->Specs_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XColor_hist_Start(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XColor_hist_IsDone(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XColor_hist_IsIdle(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XColor_hist_IsReady(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XColor_hist_EnableAutoRestart(XColor_hist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XColor_hist_DisableAutoRestart(XColor_hist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XColor_hist_Set_imageptr(XColor_hist *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IMAGEPTR_DATA, Data);
}

u32 XColor_hist_Get_imageptr(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IMAGEPTR_DATA);
    return Data;
}

void XColor_hist_Set_feature_r(XColor_hist *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_FEATURE_R_DATA, Data);
}

u32 XColor_hist_Get_feature_r(XColor_hist *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_FEATURE_R_DATA);
    return Data;
}

u32 XColor_hist_Get_specs_BaseAddress(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_BASE);
}

u32 XColor_hist_Get_specs_HighAddress(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH);
}

u32 XColor_hist_Get_specs_TotalBytes(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH - XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + 1);
}

u32 XColor_hist_Get_specs_BitWidth(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOLOR_HIST_SPECS_WIDTH_SPECS;
}

u32 XColor_hist_Get_specs_Depth(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOLOR_HIST_SPECS_DEPTH_SPECS;
}

u32 XColor_hist_Write_specs_Words(XColor_hist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH - XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XColor_hist_Read_specs_Words(XColor_hist *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH - XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + (offset + i)*4);
    }
    return length;
}

u32 XColor_hist_Write_specs_Bytes(XColor_hist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH - XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XColor_hist_Read_specs_Bytes(XColor_hist *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOLOR_HIST_SPECS_ADDR_SPECS_HIGH - XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Specs_BaseAddress + XCOLOR_HIST_SPECS_ADDR_SPECS_BASE + offset + i);
    }
    return length;
}

void XColor_hist_InterruptGlobalEnable(XColor_hist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_GIE, 1);
}

void XColor_hist_InterruptGlobalDisable(XColor_hist *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_GIE, 0);
}

void XColor_hist_InterruptEnable(XColor_hist *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IER);
    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XColor_hist_InterruptDisable(XColor_hist *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IER);
    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XColor_hist_InterruptClear(XColor_hist *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XColor_hist_WriteReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XColor_hist_InterruptGetEnabled(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_IER);
}

u32 XColor_hist_InterruptGetStatus(XColor_hist *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XColor_hist_ReadReg(InstancePtr->Control_bus_BaseAddress, XCOLOR_HIST_CONTROL_BUS_ADDR_ISR);
}

