// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCOLOR_HIST_H
#define XCOLOR_HIST_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcolor_hist_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
    u32 Specs_BaseAddress;
} XColor_hist_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 Specs_BaseAddress;
    u32 IsReady;
} XColor_hist;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XColor_hist_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XColor_hist_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XColor_hist_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XColor_hist_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XColor_hist_Initialize(XColor_hist *InstancePtr, u16 DeviceId);
XColor_hist_Config* XColor_hist_LookupConfig(u16 DeviceId);
int XColor_hist_CfgInitialize(XColor_hist *InstancePtr, XColor_hist_Config *ConfigPtr);
#else
int XColor_hist_Initialize(XColor_hist *InstancePtr, const char* InstanceName);
int XColor_hist_Release(XColor_hist *InstancePtr);
#endif

void XColor_hist_Start(XColor_hist *InstancePtr);
u32 XColor_hist_IsDone(XColor_hist *InstancePtr);
u32 XColor_hist_IsIdle(XColor_hist *InstancePtr);
u32 XColor_hist_IsReady(XColor_hist *InstancePtr);
void XColor_hist_EnableAutoRestart(XColor_hist *InstancePtr);
void XColor_hist_DisableAutoRestart(XColor_hist *InstancePtr);

void XColor_hist_Set_imageptr(XColor_hist *InstancePtr, u32 Data);
u32 XColor_hist_Get_imageptr(XColor_hist *InstancePtr);
void XColor_hist_Set_feature_r(XColor_hist *InstancePtr, u32 Data);
u32 XColor_hist_Get_feature_r(XColor_hist *InstancePtr);
u32 XColor_hist_Get_specs_BaseAddress(XColor_hist *InstancePtr);
u32 XColor_hist_Get_specs_HighAddress(XColor_hist *InstancePtr);
u32 XColor_hist_Get_specs_TotalBytes(XColor_hist *InstancePtr);
u32 XColor_hist_Get_specs_BitWidth(XColor_hist *InstancePtr);
u32 XColor_hist_Get_specs_Depth(XColor_hist *InstancePtr);
u32 XColor_hist_Write_specs_Words(XColor_hist *InstancePtr, int offset, int *data, int length);
u32 XColor_hist_Read_specs_Words(XColor_hist *InstancePtr, int offset, int *data, int length);
u32 XColor_hist_Write_specs_Bytes(XColor_hist *InstancePtr, int offset, char *data, int length);
u32 XColor_hist_Read_specs_Bytes(XColor_hist *InstancePtr, int offset, char *data, int length);

void XColor_hist_InterruptGlobalEnable(XColor_hist *InstancePtr);
void XColor_hist_InterruptGlobalDisable(XColor_hist *InstancePtr);
void XColor_hist_InterruptEnable(XColor_hist *InstancePtr, u32 Mask);
void XColor_hist_InterruptDisable(XColor_hist *InstancePtr, u32 Mask);
void XColor_hist_InterruptClear(XColor_hist *InstancePtr, u32 Mask);
u32 XColor_hist_InterruptGetEnabled(XColor_hist *InstancePtr);
u32 XColor_hist_InterruptGetStatus(XColor_hist *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
