# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XColor_hist" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_BUS_BASEADDR" \
        "C_S_AXI_CONTROL_BUS_HIGHADDR" \
        "C_S_AXI_SPECS_BASEADDR" \
        "C_S_AXI_SPECS_HIGHADDR"

    xdefine_config_file $drv_handle "xcolor_hist_g.c" "XColor_hist" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_BUS_BASEADDR" \
        "C_S_AXI_SPECS_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XColor_hist" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_BUS_BASEADDR" \
        "C_S_AXI_CONTROL_BUS_HIGHADDR" \
        "C_S_AXI_SPECS_BASEADDR" \
        "C_S_AXI_SPECS_HIGHADDR"
}

