// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcolor_hist.h"

extern XColor_hist_Config XColor_hist_ConfigTable[];

XColor_hist_Config *XColor_hist_LookupConfig(u16 DeviceId) {
	XColor_hist_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOLOR_HIST_NUM_INSTANCES; Index++) {
		if (XColor_hist_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XColor_hist_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XColor_hist_Initialize(XColor_hist *InstancePtr, u16 DeviceId) {
	XColor_hist_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XColor_hist_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XColor_hist_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

